CREATE TABLE o_rollcall(roll_number NUMBER ,name VARCHAR2(25));
CREATE TABLE n_rollcall(roll_number NUMBER ,name VARCHAR2(25));
INSERT INTO o_rollcall VALUES(45,'ASHUTOSH');
INSERT INTO o_rollcall VALUES(46,'ARYAN');
INSERT INTO o_rollcall VALUES(46,'ARYAN');
INSERT INTO o_rollcall VALUES(47,'ROHAN');
INSERT INTO o_rollcall VALUES(48,'SANKET');
INSERT INTO o_rollcall VALUES(49,'SARTHAK');
INSERT INTO o_rollcall VALUES(49,'SARTHAK');

--SHOULD BE EXECUTED ONLY ONCE
