--Opening SQL SERVER
--sudo mysql (terminal)

--VIEWING DATABASES
SHOW DATABASES;

--CREATING DATABASES
CREATE DATABASE database-name;

--USING SPECIFIC DATABASE;
USE database-name;

--CREATING TABLES IN A DATABASE (AFTER 'USE' COMMAND)
CREATE TABLE table-name(column_name DATATYPE, column_name2 DATATYPE);

--SHOW TABLES IN A DATABASE (AFTER 'USE' QUERY)
SHOW TABLES;

--DROP QUERY
DROP DATABASE/TABLE database_name/table_name;

--INSERTING VALUES INTO ROWS 
INSERT INTO table_name VALUES (val1, val2);

--SELECTING ANYTHING 
SELECT *(EVERYTHING) OR WHATEVER U WANNA SELECT FROM table_name WHERE (CONDITION); (WHERE IS OPTIONAL);

--UPDATE ROW
UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition;

--DELETING 
DELETE FROM table_name WHERE condition;

ALTER TABLE table_name ADD COLUMN/DROP column_name ;    --(MANY MORE THINGS CAN BE DONE USING ALTER)

DROP TABLE table_name;
DROP DATABASE database_name;


